<a href="https://colab.research.google.com/github/adityarajput2045/Machine-Learning-Topics/blob/main/Missing_Value_Treatment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Missing Value Treatment
# Import numpy and pandas

import numpy as np
import pandas as pd

In [19]:
# Create random datsets
data = {
    'A' : [12,15, 100, 21, 10],
    'B' : [3, np.nan, 7, 8, 9],
    'C' : [np.nan, 12, 13, 14, 15],
    'D' : [16, 17, 18, np.nan, 20]
}

df = pd.DataFrame(data)

In [20]:
df

     A    B     C     D
0   12  3.0   NaN  16.0
1   15  NaN  12.0  17.0
2  100  7.0  13.0  18.0
3   21  8.0  14.0   NaN
4   10  9.0  15.0  20.0

In [21]:
df.isnull()

       A      B      C      D
0  False  False   True  False
1  False   True  False  False
2  False  False  False  False
3  False  False  False   True
4  False  False  False  False

In [22]:
df

     A    B     C     D
0   12  3.0   NaN  16.0
1   15  NaN  12.0  17.0
2  100  7.0  13.0  18.0
3   21  8.0  14.0   NaN
4   10  9.0  15.0  20.0

In [23]:
df.isnull().sum()

A    0
B    1
C    1
D    1
dtype: int64

In [24]:
# Want to drop null row
df.dropna()

     A    B     C     D
2  100  7.0  13.0  18.0
4   10  9.0  15.0  20.0

In [25]:
df

     A    B     C     D
0   12  3.0   NaN  16.0
1   15  NaN  12.0  17.0
2  100  7.0  13.0  18.0
3   21  8.0  14.0   NaN
4   10  9.0  15.0  20.0

In [26]:
# Want to drop null coloumn
df.dropna(axis=1)

     A
0   12
1   15
2  100
3   21
4   10

In [27]:
df['B'].mean()

np.float64(6.75)

In [28]:
df['B'].fillna(df['B'].mean())

0    3.00
1    6.75
2    7.00
3    8.00
4    9.00
Name: B, dtype: float64

In [29]:
df

     A    B     C     D
0   12  3.0   NaN  16.0
1   15  NaN  12.0  17.0
2  100  7.0  13.0  18.0
3   21  8.0  14.0   NaN
4   10  9.0  15.0  20.0

In [30]:
df['B'].fillna(df['B'].median())

0    3.0
1    7.5
2    7.0
3    8.0
4    9.0
Name: B, dtype: float64

In [31]:
df['C'].fillna(0)

0     0.0
1    12.0
2    13.0
3    14.0
4    15.0
Name: C, dtype: float64

In [32]:
df['C'].fillna("Some String")

0    Some String
1           12.0
2           13.0
3           14.0
4           15.0
Name: C, dtype: object