In [319]:
# Simple Linear regression implementation using scaling and without scaling >> 
# Using Scaling vs Without Scalling
# Coef_ or slope >> Always different|
# intercept_ >> Always different
# Predictions >> Same

In [245]:
pip install numpy

Requirement already satisfied: numpy in /usr/local/python/3.14.2/lib/python3.14/site-packages (2.5.4)

[notice] A new release of pip is available: 26.2.1 -> 26.2.2
[notice] To update, run: python -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [246]:
import numpy as np;

In [247]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/python/3.14.2/lib/python3.14/site-packages (3.1.0)
Requirement already satisfied: numpy>=2.3.3 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from pandas) (2.5.4)
Requirement already satisfied: python-dateutil>=2.9.0 in /home/codespace/.local/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.14/site-packages (from python-dateutil>=2.9.0->pandas) (1.17.0)

[notice] A new release of pip is available: 26.2.1 -> 26.2.2
[notice] To update, run: python -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [248]:
import pandas as pd;

In [249]:
pip install matplotlib

Requirement already satisfied: matplotlib in /usr/local/python/3.14.2/lib/python3.14/site-packages (3.11.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from matplotlib) (1.4.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from matplotlib) (4.67.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from matplotlib) (1.5.1)
Requirement already satisfied: numpy>=1.25 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from matplotlib) (2.5.4)
Requirement already satisfied: packaging>=20.0 in /home/codespace/.local/lib/python3.14/site-packages (from matplotlib) (26.3)
Requirement already satisfied: pillow>=9 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from matplotlib) (13.0.0)
Requirement already satisfied: pyparsing>=3 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from matplotlib) (3.3.3)
Requirement already satisfied: python-dateutil>=2.7 in /home/codespace/.local/lib/python3.14/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.14/site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)

[notice] A new release of pip is available: 26.2.1 -> 26.2.2
[notice] To update, run: python -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [250]:
import matplotlib.pyplot as plt

In [293]:
df = pd.read_csv("height-weight.csv")

In [294]:
df

    Weight  Height
0       45     120
1       58     135
2       48     123
3       60     145
4       70     160
5       78     162
6       80     163
7       90     175
8       95     182
9       78     170
10      82     176
11      95     182
12     105     175
13     100     183
14      85     170
15      78     177
16      50     140
17      65     159
18      76     150
19      87     167
20      45     129
21      56     140
22      72     160

In [295]:
df.head()

   Weight  Height
0      45     120
1      58     135
2      48     123
3      60     145
4      70     160

In [296]:
df.isnull().sum()

Weight    0
Height    0
dtype: int64

In [297]:
df.head()

   Weight  Height
0      45     120
1      58     135
2      48     123
3      60     145
4      70     160

In [298]:
x = df[["Weight"]]

In [299]:
y = df["Height"]

In [300]:
x

    Weight
0       45
1       58
2       48
3       60
4       70
5       78
6       80
7       90
8       95
9       78
10      82
11      95
12     105
13     100
14      85
15      78
16      50
17      65
18      76
19      87
20      45
21      56
22      72

In [301]:
y

0     120
1     135
2     123
3     145
4     160
5     162
6     163
7     175
8     182
9     170
10    176
11    182
12    175
13    183
14    170
15    177
16    140
17    159
18    150
19    167
20    129
21    140
22    160
Name: Height, dtype: int64

In [302]:
pip install scikit-learn

Requirement already satisfied: scikit-learn in /usr/local/python/3.14.2/lib/python3.14/site-packages (1.9.1)
Requirement already satisfied: numpy>=1.24.1 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from scikit-learn) (2.5.4)
Requirement already satisfied: scipy>=1.10.0 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from scikit-learn) (1.18.1)
Requirement already satisfied: joblib>=1.4.0 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from scikit-learn) (1.6.0)
Requirement already satisfied: narwhals>=2.0.1 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from scikit-learn) (2.28.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from scikit-learn) (3.7.0)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from joblib>=1.4.0->scikit-learn) (3.1.2)

[notice] A new release of pip is available: 26.2.1 -> 26.2.2
[notice] To update, run: python -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [303]:
#linear regression parameters
#fit_intercept >> The best fit line will have intercept, by default it is true
#copy_X >> copy the original X_train and then build the model, it will not modify the original data
#n_jobs >>-1 means using all processors.
#positive>> When set to True, forces the coefficients to be positive.

#fit>> train the model
#predict>> test the model

#after building the model, you have attributes of the model
#coef_
#intercept

In [304]:
from sklearn.model_selection import train_test_split

In [305]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=1)

In [306]:
x_train.shape

(16, 1)

In [307]:
x_test.shape

(7, 1)

In [308]:
x_train

    Weight
4       70
2       48
18      76
6       80
7       90
1       58
14      85
0       45
15      78
22      72
21      56
9       78
8       95
12     105
11      95
5       78

In [309]:
x_test

    Weight
20      45
17      65
3       60
13     100
19      87
16      50
10      82

In [310]:
from sklearn.linear_model import LinearRegression

In [311]:
model = LinearRegression()

In [312]:
model

LinearRegression()

In [313]:
model.fit(x_train,y_train)

LinearRegression()

In [314]:
model.coef_

array([1.08528678])

In [315]:
model.intercept_

np.float64(76.9930174563591)

In [316]:
print("The slope and coeff of this model without scaling", model.coef_)
print("The intercept of this model without scaling", model.intercept_)

The slope and coeff of this model without scaling [1.08528678]
The intercept of this model without scaling 76.9930174563591

In [225]:
# This coef_ and intercept_ declare without scaling.
# Now we can see that coef_ and intercept_ value after doing scaling

In [275]:
scaled_model = LinearRegression()

In [276]:
scaled_model

LinearRegression()

In [277]:
# Scaling 
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [278]:
scaler

StandardScaler()

In [279]:
#scaling should be done always after train test split
#target variableshould not be scaled
#avoid scaling categorical features
x_train = scaler.fit_transform(x_train) #for train data use fit_transform
x_test = scaler.transform(x_test) #for test data use transform

In [280]:
x_train

array([[-0.33596868],
       [-1.6647437 ],
       [ 0.0264245 ],
       [ 0.26801996],
       [ 0.8720086 ],
       [-1.06075505],
       [ 0.57001428],
       [-1.84594029],
       [ 0.14722223],
       [-0.21517095],
       [-1.18155278],
       [ 0.14722223],
       [ 1.17400292],
       [ 1.77799157],
       [ 1.17400292],
       [ 0.14722223]])

In [281]:
scaled_model

LinearRegression()

In [282]:
scaled_model.fit(x_train,y_train)

LinearRegression()

In [283]:
scaled_model.coef_

array([17.96866211])

In [284]:
scaled_model.intercept_

np.float64(159.0)

In [285]:
print("The slope and coeff of this model with scaling", scaled_model.coef_)
print("The intercept of this model with scaling", scaled_model.intercept_)
print("The slope and coeff of this model without scaling", model.coef_)
print("The intercept of this model without scaling", model.intercept_)

The slope and coeff of this model with scaling [17.96866211]
The intercept of this model with scaling 159.0
The slope and coeff of this model without scaling [1.08528678]
The intercept of this model without scaling 76.9930174563591

In [286]:
#prediction on train data with scaling
#interpretation of coef>> one unit increase in weight, on average the height increase by 17.96 units
#predicted height(y) on Xtrain = 159 + 17.96 * (Xtrain)

#predicted height(y) on Xtest = 159 + 17.96 * (Xtest)

In [287]:
#prediction on train data without scaling
#interpretation of coef>> one unit increase in weight, on average the height increase by 1.08 units
#predicted height(y) on Xtrain = 77 + 1.08 * (Xtrain)

#predicted height(y) on Xtest = 77 + 1.08 * (Xtest)

In [288]:
# Now we can predict the data over x_test using scaled_model and without scaled model

In [317]:
y_pred_model = model.predict(x_train)

In [318]:
y_pred_model

array([152.96309227, 129.08678304, 159.47481297, 163.8159601 ,
       174.66882793, 139.93965087, 169.24239401, 125.83092269,
       161.64538653, 155.13366584, 137.76907731, 161.64538653,
       180.09526185, 190.94812968, 180.09526185, 161.64538653])

In [291]:
y_pred_scaled_model = scaled_model.predict(x_train)

In [292]:
y_pred_scaled_model

array([152.96309227, 129.08678304, 159.47481297, 163.8159601 ,
       174.66882793, 139.93965087, 169.24239401, 125.83092269,
       161.64538653, 155.13366584, 137.76907731, 161.64538653,
       180.09526185, 190.94812968, 180.09526185, 161.64538653])